"""Add portfolio analysis tables

Revision ID: 58f6daab96d7
Revises: 0e4d64a0bd0e
Create Date: 2025-10-24 16:00:16.097793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58f6daab96d7'
down_revision: Union[str, None] = '0e4d64a0bd0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_analysis_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('analysis_time', sa.Enum('MORNING', 'EVENING', 'MANUAL', 'ON_DEMAND', name='analysistimetype'), nullable=False),
    sa.Column('num_positions', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('cash_amount', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('portfolio_sentiment', sa.String(), nullable=True),
    sa.Column('expected_return_7d', sa.Float(), nullable=True),
    sa.Column('downside_risk_pct', sa.Float(), nullable=True),
    sa.Column('num_alerts', sa.Integer(), nullable=True),
    sa.Column('num_critical_alerts', sa.Integer(), nullable=True),
    sa.Column('num_recommendations', sa.Integer(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('data_sources_used', sa.JSON(), nullable=True),
    sa.Column('positions_data', sa.JSON(), nullable=True),
    sa.Column('correlations_data', sa.JSON(), nullable=True),
    sa.Column('risks_data', sa.JSON(), nullable=True),
    sa.Column('predictions_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_analysis_history_analysis_time'), 'portfolio_analysis_history', ['analysis_time'], unique=False)
    op.create_index(op.f('ix_portfolio_analysis_history_created_at'), 'portfolio_analysis_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_analysis_history_user_id'), 'portfolio_analysis_history', ['user_id'], unique=False)
    op.create_table('portfolio_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'OPPORTUNITY', 'INFO', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'READ', 'ACTED', 'DISMISSED', 'ARCHIVED', name='alertstatus'), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_required', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('push_notification', sa.String(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['portfolio_analysis_history.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_alerts_analysis_id'), 'portfolio_alerts', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_portfolio_alerts_created_at'), 'portfolio_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_alerts_severity'), 'portfolio_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_portfolio_alerts_status'), 'portfolio_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_portfolio_alerts_ticker'), 'portfolio_alerts', ['ticker'], unique=False)
    op.create_index(op.f('ix_portfolio_alerts_user_id'), 'portfolio_alerts', ['user_id'], unique=False)
    op.create_table('portfolio_recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('STRONG_BUY', 'BUY', 'HOLD', 'SELL', 'STRONG_SELL', name='recommendationtype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('primary_reason', sa.Text(), nullable=False),
    sa.Column('detailed_reasons', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('prediction_1d', sa.Float(), nullable=True),
    sa.Column('prediction_3d', sa.Float(), nullable=True),
    sa.Column('prediction_7d', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('fundamental_score', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['portfolio_analysis_history.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_recommendations_action'), 'portfolio_recommendations', ['action'], unique=False)
    op.create_index(op.f('ix_portfolio_recommendations_analysis_id'), 'portfolio_recommendations', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_portfolio_recommendations_created_at'), 'portfolio_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_recommendations_ticker'), 'portfolio_recommendations', ['ticker'], unique=False)
    op.create_index(op.f('ix_portfolio_recommendations_user_id'), 'portfolio_recommendations', ['user_id'], unique=False)
    op.create_table('recommendation_performance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.Enum('STRONG_BUY', 'BUY', 'HOLD', 'SELL', 'STRONG_SELL', name='recommendationtype'), nullable=False),
    sa.Column('recommendation_confidence', sa.Float(), nullable=False),
    sa.Column('price_at_recommendation', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('price_after_1d', sa.Float(), nullable=True),
    sa.Column('price_after_3d', sa.Float(), nullable=True),
    sa.Column('price_after_7d', sa.Float(), nullable=True),
    sa.Column('actual_change_1d', sa.Float(), nullable=True),
    sa.Column('actual_change_3d', sa.Float(), nullable=True),
    sa.Column('actual_change_7d', sa.Float(), nullable=True),
    sa.Column('predicted_change_1d', sa.Float(), nullable=True),
    sa.Column('predicted_change_3d', sa.Float(), nullable=True),
    sa.Column('predicted_change_7d', sa.Float(), nullable=True),
    sa.Column('accuracy_1d', sa.Float(), nullable=True),
    sa.Column('accuracy_3d', sa.Float(), nullable=True),
    sa.Column('accuracy_7d', sa.Float(), nullable=True),
    sa.Column('user_followed', sa.String(), nullable=True),
    sa.Column('user_action', sa.String(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['portfolio_recommendations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_performance_created_at'), 'recommendation_performance', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendation_performance_recommendation_id'), 'recommendation_performance', ['recommendation_id'], unique=True)
    op.create_index(op.f('ix_recommendation_performance_ticker'), 'recommendation_performance', ['ticker'], unique=False)
    op.create_index(op.f('ix_recommendation_performance_user_id'), 'recommendation_performance', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_performance_user_id'), table_name='recommendation_performance')
    op.drop_index(op.f('ix_recommendation_performance_ticker'), table_name='recommendation_performance')
    op.drop_index(op.f('ix_recommendation_performance_recommendation_id'), table_name='recommendation_performance')
    op.drop_index(op.f('ix_recommendation_performance_created_at'), table_name='recommendation_performance')
    op.drop_table('recommendation_performance')
    op.drop_index(op.f('ix_portfolio_recommendations_user_id'), table_name='portfolio_recommendations')
    op.drop_index(op.f('ix_portfolio_recommendations_ticker'), table_name='portfolio_recommendations')
    op.drop_index(op.f('ix_portfolio_recommendations_created_at'), table_name='portfolio_recommendations')
    op.drop_index(op.f('ix_portfolio_recommendations_analysis_id'), table_name='portfolio_recommendations')
    op.drop_index(op.f('ix_portfolio_recommendations_action'), table_name='portfolio_recommendations')
    op.drop_table('portfolio_recommendations')
    op.drop_index(op.f('ix_portfolio_alerts_user_id'), table_name='portfolio_alerts')
    op.drop_index(op.f('ix_portfolio_alerts_ticker'), table_name='portfolio_alerts')
    op.drop_index(op.f('ix_portfolio_alerts_status'), table_name='portfolio_alerts')
    op.drop_index(op.f('ix_portfolio_alerts_severity'), table_name='portfolio_alerts')
    op.drop_index(op.f('ix_portfolio_alerts_created_at'), table_name='portfolio_alerts')
    op.drop_index(op.f('ix_portfolio_alerts_analysis_id'), table_name='portfolio_alerts')
    op.drop_table('portfolio_alerts')
    op.drop_index(op.f('ix_portfolio_analysis_history_user_id'), table_name='portfolio_analysis_history')
    op.drop_index(op.f('ix_portfolio_analysis_history_created_at'), table_name='portfolio_analysis_history')
    op.drop_index(op.f('ix_portfolio_analysis_history_analysis_time'), table_name='portfolio_analysis_history')
    op.drop_table('portfolio_analysis_history')
    # ### end Alembic commands ###
