"""Add event impact tracking tables

Revision ID: ee2633eb4d87
Revises: 58f6daab96d7
Create Date: 2025-10-24 16:52:52.915848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee2633eb4d87'
down_revision: Union[str, None] = '58f6daab96d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_event_type_date', table_name='event_impact_history')
    op.drop_index('idx_event_type_sector', table_name='event_impact_history')
    op.drop_index('idx_ticker_event_date', table_name='event_impact_history')
    op.create_index('idx_impact_history_event_type_date', 'event_impact_history', ['event_type', 'event_date'], unique=False)
    op.create_index('idx_impact_history_event_type_sector', 'event_impact_history', ['event_type', 'sector'], unique=False)
    op.create_index('idx_impact_history_ticker_event_date', 'event_impact_history', ['ticker', 'event_date'], unique=False)
    op.create_index('idx_event_type_sector', 'event_predictions', ['event_type', 'sector'], unique=False)
    op.create_index('idx_ticker_event_date_pred', 'event_predictions', ['ticker', 'event_date'], unique=False)
    op.create_index('idx_user_event_date', 'event_predictions', ['user_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_event_predictions_created_at'), 'event_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_predictions_event_date'), 'event_predictions', ['event_date'], unique=False)
    op.create_index(op.f('ix_event_predictions_event_id'), 'event_predictions', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_predictions_event_type'), 'event_predictions', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_predictions_prediction_date'), 'event_predictions', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_event_predictions_ticker'), 'event_predictions', ['ticker'], unique=False)
    op.create_index(op.f('ix_event_predictions_user_id'), 'event_predictions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_predictions_user_id'), table_name='event_predictions')
    op.drop_index(op.f('ix_event_predictions_ticker'), table_name='event_predictions')
    op.drop_index(op.f('ix_event_predictions_prediction_date'), table_name='event_predictions')
    op.drop_index(op.f('ix_event_predictions_event_type'), table_name='event_predictions')
    op.drop_index(op.f('ix_event_predictions_event_id'), table_name='event_predictions')
    op.drop_index(op.f('ix_event_predictions_event_date'), table_name='event_predictions')
    op.drop_index(op.f('ix_event_predictions_created_at'), table_name='event_predictions')
    op.drop_index('idx_user_event_date', table_name='event_predictions')
    op.drop_index('idx_ticker_event_date_pred', table_name='event_predictions')
    op.drop_index('idx_event_type_sector', table_name='event_predictions')
    op.drop_index('idx_impact_history_ticker_event_date', table_name='event_impact_history')
    op.drop_index('idx_impact_history_event_type_sector', table_name='event_impact_history')
    op.drop_index('idx_impact_history_event_type_date', table_name='event_impact_history')
    op.create_index('idx_ticker_event_date', 'event_impact_history', ['ticker', 'event_date'], unique=False)
    op.create_index('idx_event_type_sector', 'event_impact_history', ['event_type', 'sector'], unique=False)
    op.create_index('idx_event_type_date', 'event_impact_history', ['event_type', 'event_date'], unique=False)
    # ### end Alembic commands ###
