actions_db = {
    # 🇫🇷 CAC 40
    "air liquide": "AI.PA",
    "airbus": "AIR.PA",
    "arcelormittal": "MT.AS",
    "atos": "ATO.PA",
    "axareal": "AXA.PA",
    "bnpparibas": "BNP.PA",
    "bouygues": "EN.PA",
    "capgemini": "CAP.PA",
    "carrefour": "CA.PA",
    "credit agricole": "ACA.PA",
    "danone": "BN.PA",
    "dassault systemes": "DSY.PA",
    "engie": "ENGI.PA",
    "essilorluxottica": "EL.PA",
    "hermes": "RMS.PA",
    "kering": "KER.PA",
    "l'oréal": "OR.PA",
    "lvmh": "MC.PA",
    "michelin": "ML.PA",
    "orange": "ORA.PA",
    "pernod ricard": "RI.PA",
    "publicis": "PUB.PA",
    "renault": "RNO.PA",
    "safran": "SAF.PA",
    "saint gobain": "SGO.PA",
    "sanofi": "SAN.PA",
    "schneider electric": "SU.PA",
    "societe generale": "GLE.PA",
    "stellantis": "STLAM.MI",
    "teleperformance": "TEP.PA",
    "thales": "HO.PA",
    "totalenergies": "TTE.PA",
    "unibail rodamco": "URW.AS",
    "veolia": "VIE.PA",
    "vinci": "DG.PA",
    "vivendi": "VIV.PA",

    # 🇺🇸 S&P 500 + 🇺🇸 
    "3m": "MMM",
"abbott laboratories": "ABT",
"abbvie": "ABBV",
"accenture": "ACN",
"activision blizzard": "ATVI",
"adm": "ADM",
"adobe": "ADBE",
"advanced micro devices": "AMD",
"aes corporation": "AES",
"aes": "AES",
"aetna": "AET",
"aflac": "AFL",
"agilent technologies": "A",
"air products and chemicals": "APD",
"alaska air": "ALK",
"albemarle": "ALB",
"alexandria real estate": "ARE",
"align technology": "ALGN",
"allegion": "ALLE",
"alliant energy": "LNT",
"allstate": "ALL",
"alphabet a": "GOOGL",
"alphabet c": "GOOG",
"alta": "ULTA",
"altria group": "MO",
"amazon": "AMZN",
"amd": "AMD",
"american electric power": "AEP",
"american express": "AXP",
"american international group": "AIG",
"american tower": "AMT",
"american water works": "AWK",
"ameriprise": "AMP",
"amerisourcebergen": "ABC",
"amgen": "AMGN",
"amphenol": "APH",
"analog devices": "ADI",
"ansys": "ANSS",
"anthem": "ANTM",
"aon": "AON",
"apache": "APA",
"apple": "AAPL",
"applied materials": "AMAT",
"arch capital": "ACGL",
"archer daniels midland": "ADM",
"argonaut gold": "ARNGF",
"arista networks": "ANET",
"arthur j. gallagher": "AJG",
"assurant": "AIZ",
"at&t": "T",
"autodesk": "ADSK",
"autozone": "AZO",
"avalonbay communities": "AVB",
"avery dennison": "AVY",
"baker hughes": "BKR",
"ball corp": "BALL",
"bank of america": "BAC",
"baxter international": "BAX",
"becton dickinson": "BDX",
"berkshire hathaway": "BRK-B",
"best buy": "BBY",
"biogen": "BIIB",
"bio-rad laboratories": "BIO",
"blackrock": "BLK",
"booking holdings": "BKNG",
"boston properties": "BXP",
"boston scientific": "BSX",
"bristol-myers squibb": "BMY",
"broadridge financial": "BR",
"brown & brown": "BRO",
"brown-forman": "BF-B",
"c.h. robinson": "CHRW",
"caesars entertainment": "CZR",
"camden property trust": "CPT",
"campbell soup": "CPB",
"capital one": "COF",
"cardinal health": "CAH",
"carmax": "KMX",
"carnival": "CCL",
"caterpillar": "CAT",
"cboe global markets": "CBOE",
"cbre group": "CBRE",
"cdw": "CDW",
"celanese": "CE",
"centene": "CNC",
"centerpoint energy": "CNP",
"ceridian": "CDAY",
"cf industries": "CF",
"charles river": "CRL",
"charles schwab": "SCHW",
"charter communications": "CHTR",
"chevron": "CVX",
"chipotle": "CMG",
"chubb": "CB",
"church & dwight": "CHD",
"cigna": "CI",
"cincinnati financial": "CINF",
"cintas": "CTAS",
"cisco systems": "CSCO",
"citigroup": "C",
"clorox": "CLX",
"cme group": "CME",
"cms energy": "CMS",
"coca-cola": "KO",
"cognizant": "CTSH",
"colgate-palmolive": "CL",
"comcast": "CMCSA",
"comerica": "CMA",
"conagra": "CAG",
"conocophillips": "COP",
"consolidated edison": "ED",
"constellation brands": "STZ",
"constellation energy": "CEG",
"corning": "GLW",
"corteva": "CTVA",
"costco": "COST",
"coty": "COTY",
"crown castle": "CCI",
"csx": "CSX",
"cummins": "CMI",
"cvs health": "CVS",
"d.r. horton": "DHI",
"danaher": "DHR",
"darden restaurants": "DRI",
"davita": "DVA",
"deere": "DE",
"delta air lines": "DAL",
"dentsply sirona": "XRAY",
"devon energy": "DVN",
"dexcom": "DXCM",
"diamondback energy": "FANG",
"digital realty": "DLR",
"discover": "DFS",
"disney": "DIS",
"dish network": "DISH",
"dominion energy": "D",
"dover": "DOV",
"dow": "DOW",
"dte energy": "DTE",
"duke energy": "DUK",
"dupont": "DD",
"dxc technology": "DXC",
"eastman chemical": "EMN",
"eaton": "ETN",
"ebay": "EBAY",
"ecolab": "ECL",
"edison international": "EIX",
"edwards lifesciences": "EW",
"electronic arts": "EA",
"emerson electric": "EMR",
"enphase energy": "ENPH",
"entergy": "ETR",
"equifax": "EFX",
"equity residential": "EQR",
"essex property trust": "ESS",
"esterline": "ESL",
"estee lauder": "EL",
"evergy": "EVRG",
"everest re": "RE",
"everest re group": "EG",
"eversource energy": "ES",
"exelon": "EXC",
"expedia": "EXPE",
"expeditors international": "EXPD",
"extra space storage": "EXR",
"exxonmobil": "XOM",
"f5": "FFIV",
"factset": "FDS",
"fastenal": "FAST",
"federal realty": "FRT",
"fidelity national info": "FIS",
"fifth third bancorp": "FITB",
"first republic": "FRC",
"first solar": "FSLR",
"fiserv": "FI",
"fleetcor": "FLT",
"flir": "FLIR",
"florida power & light": "NEE",
"florida power and light": "NEE",
"flour corp": "FLR",
"fmc": "FMC",
"ford motor": "F",
"fortinet": "FTNT",
"fortive": "FTV",
"fox corp a": "FOXA",
"fox corp b": "FOX",
"franklin resources": "BEN",
"freeport-mcmoran": "FCX",
"gap": "GPS",
"garmin": "GRMN",
"gartner": "IT",
"generac": "GNRC",
"general dynamics": "GD",
"general electric": "GE",
"general mills": "GIS",
"genuine parts": "GPC",
"gilead sciences": "GILD",
"global payments": "GPN",
"goldman sachs": "GS",
"halliburton": "HAL",
"hartford financial": "HIG",
"hasbro": "HAS",
"hca healthcare": "HCA",
"healthpeak properties": "PEAK",
"henry schein": "HSIC",
"hershey": "HSY",
"hewlett packard enterprise": "HPE",
"hilton": "HLT",
"hollyfrontier": "HFC",
"honeywell": "HON",
"hornbeck offshore": "HOS",
"host hotels": "HST",
"hp inc": "HPQ",
"humana": "HUM",
"hunt jb transport": "JBHT",
"huntington bancshares": "HBAN",
"hvac holdings": "HVAC",
"ibi group": "IBI",
"icahn enterprises": "IEP",
"idex corp": "IEX",
"idexx laboratories": "IDXX",
"illumina": "ILMN",
"imperial brands": "IMBBY",
"incitec pivot": "INCZY",
"incyte": "INCY",
"intel": "INTC",
"intercontinental exchange": "ICE",
"international business machines": "IBM",
"international flavors & fragrances": "IFF",
"international paper": "IP",
"interpublic group": "IPG",
"intuit": "INTU",
"intu properties": "ITUPF",
"invesco": "IVZ",
"ipg photonics": "IPGP",
"iqvia": "IQV",
"iron mountain": "IRM",
"j.b. hunt": "JBHT",
"jacobs engineering": "J",
"jm smucker": "SJM",
"johnson & johnson": "JNJ",
"johnson controls": "JCI",
"jpmorgan chase": "JPM",
"juniper networks": "JNPR",
"kansas city southern": "KSU",
"kellogg": "K",
"keycorp": "KEY",
"keysight technologies": "KEYS",
"kimberly-clark": "KMB",
"kimco realty": "KIM",
"kinder morgan": "KMI",
"kraft heinz": "KHC",
"kraft foods": "KFT",
"kroger": "KR",
"l3harris": "LHX",
"laboratory corp of america": "LH",
"lam research": "LRCX",
"leggett & platt": "LEG",
"leidos": "LDOS",
"lennar": "LEN",
"leroy seafood": "LSFHF",
"less": "LESS",
"lexmark": "LXK",
"liberty global": "LBTYA",
"liberty media": "FWONA",
"lilly eli": "LLY",
"lincoln financial": "LNC",
"linde": "LIN",
"live nation": "LYV",
"lkq corp": "LKQ",
"lockheed martin": "LMT",
"loews": "L",
"lowe's": "LOW",
"lumen technologies": "LUMN",
"lyondellbasell": "LYB",
"m&t bank": "MTB",
"marathon oil": "MRO",
"marathon petroleum": "MPC",
"marsh & mclennan": "MMC",
"martin marietta": "MLM",
"masco": "MAS",
"mastercard": "MA",
"match group": "MTCH",
"mattel": "MAT",
"mcdonald's": "MCD",
"mcgraw hill financial": "MHFI",
"mdlz": "MDLZ",
"medtronic": "MDT",
"merck & co": "MRK",
"metlife": "MET",
"microsoft": "MSFT",
"mid-america apartment": "MAA",
"moderna": "MRNA",
"mohawk industries": "MHK",
"molina healthcare": "MOH",
"mondelez": "MDLZ",
"monolithic power": "MPWR",
"monster beverage": "MNST",
"moodys": "MCO",
"morgan stanley": "MS",
"mosaic": "MOS",
"motorola solutions": "MSI",
"msci": "MSCI",
"nasdaq": "NDAQ",
"national grid": "NGG",
"national oilwell varco": "NOV",
"newell brands": "NWL",
"newmont": "NEM",
"news corp": "NWSA",
"nextEra energy": "NEE",
"nike": "NKE",
"nordson": "NDSN",
"northern trust": "NTRS",
"northrop grumman": "NOC",
"nortonlifelock": "NLOK",
"norwegian cruise line": "NCLH",
"nrg energy": "NRG",
"nucor": "NUE",
"nvidia": "NVDA",
"nvr": "NVR",
"nvr inc": "NVR",
"nxp semiconductors": "NXPI",
"o'reilly automotive": "ORLY",
"occidental petroleum": "OXY",
"omnicom": "OMC",
"oneok": "OKE",
"oracle": "ORCL",
"organon": "OGN",
"otis worldwide": "OTIS",
"paccar": "PCAR",
"packaging corp of america": "PKG",
"paramount global": "PARA",
"parker hannifin": "PH",
"paychex": "PAYX",
"paypal": "PYPL",
"pentair": "PNR",
"pepco holdings": "POM",
"pepsico": "PEP",
"perkinelmer": "PKI",
"pfizer": "PFE",
"philip morris": "PM",
"phillips 66": "PSX",
"pinnacle west": "PNW",
"pioneer natural resources": "PXD",
"pnc financial": "PNC",
"pool corp": "POOL",
"ppg industries": "PPG",
"ppl corporation": "PPL",
"principal financial": "PFG",
"procter & gamble": "PG",
"progressive corp": "PGR",
"prologis": "PLD",
"prudential financial": "PRU",
"pseg": "PEG",
"ptc": "PTC",
"public service enterprise": "PEG",
"pultegroup": "PHM",
"qorvo": "QRVO",
"qualcomm": "QCOM",
"quest diagnostics": "DGX",
"raymond james": "RJF",
"raytheon technologies": "RTX",
"realty income": "O",
"republic services": "RSG",
"resmed": "RMD",
"reynolds consumer": "REYN",
"robert half": "RHI",
"rockwell automation": "ROK",
"roper technologies": "ROP",
"ross stores": "ROST",
"royal caribbean": "RCL",
"s&p global": "SPGI",
"salesforce": "CRM",
"sba communications": "SBAC",
"schlumberger": "SLB",
"seagate": "STX",
"sealed air": "SEE",
"seattle genetics": "SGEN",
"sempra energy": "SRE",
"sherwin-williams": "SHW",
"skyworks solutions": "SWKS",
"sl green": "SLG",
"smith & nephew": "SNN",
"smith a.o.": "AOS",
"smucker": "SJM",
"snc-lavalin": "SNCAF",
"sofi": "SOFI",
"solaredge": "SEDG",
"southern company": "SO",
"southwest airlines": "LUV",
"southwest gas": "SWX",
"spglobal": "SPGI",
"spx corp": "SPXC",
"ssl": "SSL",
"st. jude medical": "STJ",
"staar surgical": "STAA",
"stanley black & decker": "SWK",
"starbucks": "SBUX",
"state street": "STT",
"steven madden": "SHOO",
"steris": "STE",
"straumann": "SAUHF",
"stryker": "SYK",
"sun communities": "SUI",
"sunrun": "RUN",
"svb financial": "SIVB",
"synchrony financial": "SYF",
"synopsys": "SNPS",
"sysco": "SYY",
"t rowe price": "TROW",
"t-mobile us": "TMUS",
"tapestry": "TPR",
"targa resources": "TRGP",
"te connectivity": "TEL",
"teledyne technologies": "TDY",
"teleflex": "TFX",
"teradyne": "TER",
"texas instruments": "TXN",
"textron": "TXT",
"thermo fisher": "TMO",
"thor industries": "THO",
"tiffany & co": "TIF",
"time warner": "TWX",
"toll brothers": "TOL",
"toro": "TTC",
"totalenergies (adr)": "TTE",
"tractor supply": "TSCO",
"trane technologies": "TT",
"transdigm group": "TDG",
"transocean": "RIG",
"travelers": "TRV",
"trinet": "TNET",
"trugreen": "TG",
"trupanion": "TRUP",
"tyson foods": "TSN",
"u.s. bancorp": "USB",
"ulta beauty": "ULTA",
"ultra clean holdings": "UCTT",
"under armour a": "UAA",
"under armour c": "UA",
"union pacific": "UNP",
"united airlines": "UAL",
"united parcel service": "UPS",
"united rentals": "URI",
"unitedhealth group": "UNH",
"universal health services": "UHS",
"unum group": "UNM",
"valero energy": "VLO",
"ventas": "VTR",
"verisign": "VRSN",
"verisk analytics": "VRSK",
"verizon": "VZ",
"vertex pharmaceuticals": "VRTX",
"vf corp": "VFC",
"viacomcbs": "VIAC",
"vici properties": "VICI",
"visa": "V",
"vistra corp": "VST",
"vmware": "VMW",
"vornado realty trust": "VNO",
"voyager therapeutics": "VYGR",
"walgreens boots alliance": "WBA",
"walmart": "WMT",
"walt disney": "DIS",
"warner bros discovery": "WBD",
"waste management": "WM",
"waters corp": "WAT",
"watsco": "WSO",
"wells fargo": "WFC",
"west pharmaceutical": "WST",
"western digital": "WDC",
"western union": "WU",
"westinghouse air brake": "WAB",
"westrock": "WRK",
"weyerhaeuser": "WY",
"whirlpool": "WHR",
"willis towers watson": "WTW",
"williams companies": "WMB",
"willsco": "WSCO",
"winnebago industries": "WGO",
"winn-dixie": "WINN",
"workday": "WDAY",
"wpp": "WPP",
"ww grainger": "GWW",
"wynn resorts": "WYNN",
"xcel energy": "XEL",
"xerox": "XRX",
"xilinx": "XLNX",
"xylem": "XYL",
"yahoo": "YHOO",
"yelp": "YELP",
"yeti holdings": "YETI",
"yrc worldwide": "YRCW",
"yum brands": "YUM",
"yum china": "YUMC",
"zebra technologies": "ZBRA",
"zimmer biomet": "ZBH",
"zions bancorp": "ZION",
"zoetis": "ZTS",
"zoom video": "ZM",


# Nasdaq 100
"activision blizzard": "ATVI",
"adobe": "ADBE",
"advanced micro devices": "AMD",
"align technology": "ALGN",
"alphabet a": "GOOGL",
"alphabet c": "GOOG",
"amazon": "AMZN",
"amd": "AMD",
"american electric power": "AEP",
"amgen": "AMGN",
"analog devices": "ADI",
"ansys": "ANSS",
"apple": "AAPL",
"autodesk": "ADSK",
"automatic data processing": "ADP",
"booking holdings": "BKNG",
"cadence design systems": "CDNS",
"cisco systems": "CSCO",
"cintas": "CTAS",
"comcast": "CMCSA",
"costco": "COST",
"csx": "CSX",
"datadog": "DDOG",
"dexcom": "DXCM",
"dollar tree": "DLTR",
"dollar general": "DG",
"ebay": "EBAY",
"electronic arts": "EA",
"exelon": "EXC",
"expedia": "EXPE",
"fastenal": "FAST",
"fortinet": "FTNT",
"gilead sciences": "GILD",
"intel": "INTC",
"intuit": "INTU",
"jd.com": "JD",
"lam research": "LRCX",
"lululemon athletica": "LULU",
"marriott international": "MAR",
"match group": "MTCH",
"meta": "META",
"microchip technology": "MCHP",
"micron": "MU",
"microsoft": "MSFT",
"moderna": "MRNA",
"monolithic power systems": "MPWR",
"netflix": "NFLX",
"nvidia": "NVDA",
"nortonlifelock": "NLOK",
"nrg energy": "NRG",
"nrg inc": "NRG",
"nxp semiconductors": "NXPI",
"okta": "OKTA",
"on semiconductor": "ON",
"paypal": "PYPL",
"pepsico": "PEP",
"pinduoduo": "PDD",
"qualcomm": "QCOM",
"roberts half": "RHI",
"ross stores": "ROST",
"seagate technology": "STX",
"seagen": "SGEN",
"sirius xm": "SIRI",
"skyworks solutions": "SWKS",
"splunk": "SPLK",
"synopsys": "SNPS",
"take-two interactive": "TTWO",
"tesla": "TSLA",
"texas instruments": "TXN",
"t-mobile us": "TMUS",
"verisign": "VRSN",
"verisk analytics": "VRSK",
"vertex pharmaceuticals": "VRTX",
"vitesse": "VTSS",
"vulcan materials": "VMC",
"wd-40": "WDFC",
"workday": "WDAY",
"xcel energy": "XEL",
"xilinx": "XLNX",
"yahoo": "YHOO",
"yandex": "YNDX",
"zebra technologies": "ZBRA",
"zoom video": "ZM",
"zscaler": "ZS",
"lucid group": "LCID",
"rivian automotive": "RIVN",
"robinhood markets": "HOOD",
"palantir technologies": "PLTR",
"coupang": "CPNG",
"datadog": "DDOG",
"crowdstrike": "CRWD",
"snowflake": "SNOW",
"coinbase": "COIN",
"palo alto networks": "PANW",
"airbnb": "ABNB",
"doordash": "DASH",
"lyft": "LYFT",
"uber": "UBER",
"zoominfo": "ZI",
"docuSign": "DOCU",


# 🇫🇷 Midcap / SBF120
"valneva": "VLA.PA",
"remy cointreau": "RCO.PA",
"biomerieux": "BIM.PA",
"solutions 30": "S30.PA",
"soitec": "SOI.PA",
"virbac": "VIRP.PA",

# 🌍 Global
"alibaba": "BABA",
"samsung": "005930.KQ",
"toyota": "7203.T",
"tencent": "0700.HK",
"shell": "SHEL.L",
"novartis": "NOVN.SW"

}
